# Generated by Django 4.1.6 on 2023-02-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sections', models.IntegerField(default=5)),
                ('post', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
